Repository oke-aditya/pytorch_cnn_trainer, pull requests merged in 2020-10, with the labels that each got.

#23 Added history like object as in Keras
  examples/train_step_example.py
  pytorch_cnn_trainer/engine.py
  tests/test_fit_metrics.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#26 Adds Lightning Trainer and Example
  .gitignore
  examples/lightning_train.py
  pytorch_cnn_trainer/lightning_trainer.py
  settings.ini
  tests/test_lightning_trainer.py
Labels: enhancement, priority

#25 Adds plotter utility
  pytorch_cnn_trainer/__init__.py
  pytorch_cnn_trainer/engine.py
  pytorch_cnn_trainer/plotter.py
  tests/test_plotting.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
